package words

// 26

func (w *Words) setWordsEn() {
	w.en["1"] = "one"
	w.en["2"] = "two"
	w.en["tiUjeVocheredi"] = "you are already in line"
	w.en["zapustilOchered"] = " started the queue "
	w.en["ocheredKz"] = "Queue rs"
	w.en["min."] = "min."
	w.en["prinuditelniStart"] = "forced start"
	w.en["SborNaKz"] = "Collection on rs"
	w.en["кз"] = "rs"
	w.en["tiUjePodpisanNaKz"] = "you are already subscribed to rs"
	w.en["dlyaDobavleniyaVochered"] = "to add to the queue write"
	w.en["viPodpisalisNaPing"] = "you subscribed to ping rs"
	w.en["tiNePodpisanNaPingKz"] = "you are not subscribed to ping rs"
	w.en["otpisalsyaOtPingaKz"] = "unsubscribed from ping rs"
	w.en["prisoedenilsyKocheredi"] = " joined the queue"
	w.en["nujenEsheOdinDlyFulki"] = "need another one for the full line"
	w.en["sformirovana"] = "formed"
	w.en["Vigru"] = "in Game"
	w.en["zakrilOcheredKz"] = "closed the queue of rs"
	w.en["tiNeVOcheredi"] = "you're out of line"
	w.en["pokinulOchered"] = " left the queue"
	w.en["bilaUdalena"] = "was deleted"
	w.en["dly ustanovki"] = " To set emoji, write text \nEmoji space (cell number 1-4) space Emoji \n example \nEmoji 1 🚀\n Your slots"
	w.en["vashiEmodji"] = "Your emoji\n"
	w.en["dly iventa"] = "for the event"
	w.en["iventZapushen"] = "Event started. After each trip to the RS, one of the participants in the RS contributes the points received to the base by the team K (skating rink number) (number of points scored)"
	w.en["rejimIventaUje"] = "Event mode is already activated."
	w.en["zapuskIostanovka"] = "Launch | Stopping the Event is available to the Channel Administrator."
	w.en["IventOstanovlen"] = "Event stopped."
	w.en["iventItakAktiven"] = "The event is not active. Nothing to stop"
	w.en["dannieKzUjeVneseni"] = "rs data already entered"
	w.en["ochki vnesen"] = "Points added to database"
	w.en["dobavlenieOchkovNevozmojno"] = "points cannot be added. You are not a member of the KZ under the number"
	w.en["iventNeZapushen"] = "Event not started."
	w.en["iventIgra"] = "event game"
	w.en["vneseno"] = "contributed"
	w.en["VremyaPochtiVishlo"] = " time is almost up...\nTo extend the waiting time by 30m press +\nTo exit the queue press -"
	w.en["ranovatoPlysik"] = "too early to press the plus sign, you are in line for rs"
	w.en["budeshEshe"] = "you will still"
	w.en["vremyaObnovleno"] = " time updated "
	w.en["ranovatoMinus"] = "too early minus press, you're in line for rs"
	w.en["pusta"] = " empty "
	w.en["netAktivnuh"] = "No active queues "
	w.en["prinuditelniStartDostupen"] = "Forced start is available to queue members."
	w.en["bilaZapushenaNe"] = "was launched incomplete"
	w.en["maksimalnoeVremya"] = "the maximum time in the queue is limited to 180 minutes\n  your time"
	w.en["vremyaObnovleno"] = " time updated +30"
	w.en["ScanDB"] = "Scanning the database"
	w.en["noHistory"] = " History not found "
	w.en["formlist"] = "Forming a list "
	w.en["topUchastnikov"] = "TOP Participants"
	w.en["iventa"] = "event"
	w.en["teperViPodpisani"] = "You are now subscribed to"
	w.en["ViUjePodpisan"] = "You are already subscribed to"
	w.en["oshibkaNedostatochno"] = "error: insufficient privileges to grant role "
	w.en["viNePodpisani"] = "You are not subscribed to the role"
	w.en["netTakoiRoli"] = "there is no such role on the server"
	w.en["ViOtpisalis"] = "You have unsubscribed from the role"
	w.en["OshibkaNedostatochnadlyaS"] = "error: insufficient rights to remove role "
	w.en["jelaushieNa"] = "Wishing to"
	w.en["DlyaDobavleniya"] = "to add to the queue"
	w.en["DlyaVihodaIz"] = "to exit the queue"
	w.en["DannieObnovleni"] = "Data updated"

}
